project_id = "jptlmxxwbrmwcmevbvwj"

[functions.selection-breeding]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.system-control]
verify_jwt = false

[functions.coinbase-test]
verify_jwt = false

[functions.coinbase-balances]
verify_jwt = false

[functions.paper-execute]
verify_jwt = false

[functions.paper-reset]
verify_jwt = false

[functions.market-poll]
verify_jwt = false

[functions.trade-execute]
verify_jwt = false

[functions.trade-cycle]
verify_jwt = false

[functions.fitness-calc]
verify_jwt = false

[functions.generation-start]
verify_jwt = false

[functions.arm-live]
verify_jwt = false

[functions.news-poll]
verify_jwt = false

[functions.news-feed]
verify_jwt = false

[functions.price-feed]
verify_jwt = false

[functions.missed-moves]
verify_jwt = false
