project_id = "jptlmxxwbrmwcmevbvwj"

[functions.system-control]
verify_jwt = false

[functions.market-poll]
verify_jwt = false

[functions.coinbase-test]
verify_jwt = false

[functions.coinbase-balances]
verify_jwt = false